FocSubGrp:= function(arg)
    # Computes the focal subgroup \Phi^{G}(H)
    local G,H,HGrep,dengen,x,h;
    G:=arg[1]; # our group G
    if Length(arg)=1 then
        H:=Stabilizer(G,1); # if no other group is given, then H is the stabiliser of 1
    else
        H:=arg[2];
    fi;

    if GeneratorsOfGroup(H)=[] then 
        return []; # if H is the trivial subgroup, then the focal subgroup is trivial
    fi;

    HGrep:=List(RightCosets(G,H),Representative); # list of right coset reps
    dengen:=ShallowCopy(GeneratorsOfGroup(DerivedSubgroup(H))); # list of generators of [H,H]

    for x in HGrep do
        for h in GeneratorsOfGroup(Intersection(H,H^x)) do
            Add(dengen, Comm(h,x^-1)); # add the commutator [h,x^-1] to the set of [H,H] gens
        od;
    od; # at this point dengen is a list of generators of the focal subgroup
    return Group(dengen, Identity(G)); # group generated by dengen
end;

Kercheck:= function(n,i,m,j)
    # this function checks if the kernel of the natural map F(GG,HH) -> F(GG,XX) is trivial 
    # where GG is a Schur cover of G=nTi \wr mTj, XX the pullback of Y= nTi \rtimes Stab_{mTj}(1), 
    # and HH the pullback of H = Stab_{G}(1) 

    local G,H,pi,Y,epi,GG,HH,XX,HGrep,FocHgen,GGHHrep,XGrep,FocXgen,GGXXrep,k,imh,l,imx,den,num;

    G:=WreathProductImprimitiveAction(TransitiveGroup(n,i), TransitiveGroup(m,j)); # nTi \wr mTj
    H:=Stabilizer(G,1);
    pi:=Projection(G); # the surjection from G onto mTj
    Y:=PreImage(pi, Stabilizer(TransitiveGroup(m,j), 1)); # our group Y = nTi \rtimes Stab_{mTj}(1)
    epi:=EpimorphismSchurCover(G); # the surjection from the Schur cover down to G
    GG:=Source(epi); # the Schur cover
    HH:=PreImage(epi,H); # pullback of H
    XX:=PreImage(epi,Y); # pullback of Y

    # Easy cases
    if GeneratorsOfGroup(HH)=[] then 
        return []; # if HH is trivial, kernel is definitely trivial
    fi;

    if GeneratorsOfGroup(XX)=[] then
        return []; # if XX is trivial, the kernel is definitely trivial
    fi;

    # Make a list of the generators for Phi^{GG}(HH)
    HGrep:=List(RightCosets(G,H),Representative); # right coset H\G reps
    FocHgen:=ShallowCopy(GeneratorsOfGroup(DerivedSubgroup(HH))); # generators of [HH,HH]
    GGHHrep:=List(HGrep,x->PreImagesRepresentative(epi,x)^-1); # preimage^{-1} of right coset H\G reps
    
    for k in [1..Length(HGrep)] do
        for imh in GeneratorsOfGroup(Intersection(H,H^HGrep[k])) do
            Add(FocHgen,Comm(PreImagesRepresentative(epi,imh),GGHHrep[k]));
            # for each right coset H\G representative g and each element h in a generating set of 
            # (H \cap g^{-1}Hg), add to the list of [HH,HH] generators the commutator [hh,gg^{-1}]
            # where hh is a preimage of h and gg that of g  
        od;
    od;

    # Make a list of the generators for Phi^{GG}(XX)
    XGrep:=List(RightCosets(G,Y),Representative); # right coset Y\G reps
    FocXgen:=ShallowCopy(GeneratorsOfGroup(DerivedSubgroup(XX))); # generators of [XX,XX]
    GGXXrep:=List(XGrep,x->PreImagesRepresentative(epi,x)^-1); # preimage of right coset Y\G reps

    for l in [1..Length(XGrep)] do
        for imx in GeneratorsOfGroup(Intersection(Y,Y^XGrep[l])) do
            Add(FocXgen,Comm(PreImagesRepresentative(epi,imx),GGXXrep[l]));
            # Same logic as with the previous nested for loop
        od;
    od;

    den:=Group(FocHgen); # our group Phi^{GG}(HH)
    num:=Intersection(Group(FocXgen), HH); # the group Phi^{GG}(XX) \cap HH
    return AbelianInvariants(num/den); # the quotient (Phi^{GG}(XX) \cap HH)/Phi^{GG}(HH)
end;

IsKerTriv := function(d)
    # take in an integer d and output a csv file where each line is of the from
    # [ m, i ], [ d/m, j ], [ K ]
    # where m runs through all divisors of d (apart from 1 and d), i runs from 1 to the number of 
    # transitive subgroups of S_m, and j runs from 1 to the number of transitive subgroups of S_{d/m}.
    # Here K is the output of the function Kercheck(m,i,d/m,j), that is the kernel of the natural 
    # map F(GG,HH) -> F(GG,XX), where GG is a Schur cover of G=mTi \wr d/mTj

	local output, m, i, j;
    output := Concatenation("ConjCheck/IsKerTriv_output_", String(d), ".csv");
    # output is a csv file with name IsKerTriv_output_d.csv

    PrintTo(output, "T, B, Ker\n");

    for m in Filtered(DivisorsInt(d), x-> 1 < x and x < d) do # for each proper nontrivial divisor of d
        for i in [1.. NrTransitiveGroups(m)] do # each transitive subgroup of S_{m}
            for j in [1.. NrTransitiveGroups(d/m)] do # each transitive subgroup of S_{d/m}
                AppendTo(output,
                    Concatenation(
                    String([m,i]), ", ",
                    String([d/m,j]), ", ",
                    String(Kercheck(m,i,d/m,j)), "\n"
                    )
                );
            od;
	    od;
    od; 
end;




